version: '3.8'
services:
  postgres:
    container_name: teste-logico-postgres-bti
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testeLogicoPostgresBTI
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: teste-logico-api-bti
    image: teste-logico-api-bti
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE__HOST=postgres
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=postgres
      - DATABASE__PASSWORD=postgres
      - DATABASE__NAME=testeLogicoPostgresBTI

  migrations:
    container_name: teste-logico-api-migrations-bti
    image: teste-logico-api-migrations-bti
    build:
      context: ../
      dockerfile: Dockerfile.migrations
    depends_on:
      - postgres
    environment:
      - DATABASE__HOST=postgres
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=postgres
      - DATABASE__PASSWORD=postgres
      - DATABASE__NAME=testeLogicoPostgresBTI

volumes:
  postgres: